-- liquibase formatted sql

-- changeset caveri:1



CREATE TABLE notification_tasks
(

    id                     BIGINT generated by default as identity PRIMARY KEY,
    message                TEXT,
    chat_id                BIGINT    NOT NULL,
    notification_date_time TIMESTAMP NOT NULL
);